spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/vizsgaremek_sql
spring.datasource.username=root
spring.datasource.password=root

logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.orm.jdbc.bind=trace

spring.profiles.active=dev
spring.security.user.name=username
spring.security.user.password=password

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= konyvaura@gmail.com
spring.mail.password= KonyvAura1478!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.main.allow-bean-definition-overriding=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=100MB

jwt.secret=d61eb086b07afb8b3860ce61a47783fc9a8b6074eb61b518a97a2c0dc961730f
jwt.issuer=KonyvAura
jwt.expiredTime=7200000

spring.web.resources.static-locations=file:./images/,classpath:/static/
